# Generated by Django 4.0.2 on 2022-02-19 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_activationcode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activationcode',
            old_name='created_by',
            new_name='user_id',
        ),
        migrations.RemoveField(
            model_name='activationcode',
            name='report_type',
        ),
        migrations.AddField(
            model_name='activationcode',
            name='activation_code',
            field=models.PositiveIntegerField(default=None, unique=True),
            preserve_default=False,
        ),
    ]
