# Generated by Django 4.0.2 on 2022-02-19 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0003_rename_created_by_activationcode_user_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activationcode',
            old_name='user_id',
            new_name='user',
        ),
    ]
