# Generated by Django 4.0.2 on 2022-02-20 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0004_rename_user_id_activationcode_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='space',
            name='thumbnail',
            field=models.FilePathField(default='/thumbnails/users/'),
        ),
        migrations.AddField(
            model_name='user',
            name='about',
            field=models.CharField(default=None, max_length=500),
        ),
    ]
