# Generated by Django 4.0.2 on 2022-02-21 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0005_space_thumbnail_user_about'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attachment',
            old_name='post_id',
            new_name='post',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='post_id',
            new_name='post',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='space_id',
            new_name='space',
        ),
        migrations.RenameField(
            model_name='report',
            old_name='post_id',
            new_name='post',
        ),
        migrations.RenameField(
            model_name='spacemembership',
            old_name='space_id',
            new_name='space',
        ),
        migrations.RenameField(
            model_name='spacemembership',
            old_name='user_id',
            new_name='user',
        ),
    ]
