# Generated by Django 4.0.2 on 2022-02-21 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0006_rename_post_id_attachment_post_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spacemembership',
            old_name='user',
            new_name='followed_by',
        ),
    ]
