# Generated by Django 4.0.2 on 2022-02-21 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0007_rename_user_spacemembership_followed_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='space',
            name='thumbnail',
            field=models.FilePathField(path=None),
        ),
    ]
