# Generated by Django 4.0.2 on 2022-02-21 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0009_alter_space_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='space',
            name='thumbnail',
            field=models.FilePathField(default=None, path=None),
        ),
    ]
