# Generated by Django 4.0.2 on 2022-02-22 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0014_post_vote_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpacePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=500)),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='space_policy', to='social.space')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
