# Generated by Django 4.0.2 on 2022-03-04 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0016_alter_comment_options_alter_post_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default='aaa', max_length=200),
            preserve_default=False,
        ),
    ]
