# Generated by Django 4.0.2 on 2022-03-04 11:31

import autoslug.fields
from django.db import migrations
import social.models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0020_alter_post_slug_alter_space_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='title', slugify=social.models.slugify),
        ),
        migrations.AlterField(
            model_name='space',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='title', slugify=social.models.slugify, unique_with=('title',)),
        ),
    ]
