# Generated by Django 4.0.2 on 2022-03-04 11:32

import autoslug.fields
from django.db import migrations
import social.models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0021_alter_post_slug_alter_space_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, max_length=300, populate_from='title', slugify=social.models.slugify),
        ),
    ]
