# Generated by Django 4.0.2 on 2022-03-05 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0022_alter_post_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmarks',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
