# Generated by Django 4.0.2 on 2022-03-06 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0024_comment_parent_comment_post_comment_depth'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='depth',
            field=models.PositiveIntegerField(default=1, help_text='One means first level', null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='comment_depth',
            field=models.PositiveIntegerField(default=0, help_text='Zero means no comment', null=True),
        ),
    ]
