# Generated by Django 4.0.2 on 2022-03-09 11:03

import autoslug.fields
from django.db import migrations
import social.models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0026_comment_lft_comment_rgt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=autoslug.fields.AutoSlugField(allow_unicode=True, editable=False, max_length=300, populate_from='title', slugify=social.models.slugify),
        ),
    ]
