# Generated by Django 4.0.2 on 2022-03-09 13:09

import autoslug.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import social.models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0027_alter_post_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='invitation_counter',
            field=models.PositiveSmallIntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, max_length=300, populate_from='title', slugify=social.models.slugify),
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Email address')),
                ('unique_code', models.CharField(max_length=64)),
                ('is_used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invitor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitor_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
