# Generated by Django 4.0.2 on 2022-03-09 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0028_user_invitation_counter_alter_post_slug_invitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='display_name',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
