# Generated by Django 4.0.2 on 2022-03-14 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0029_user_display_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='show_real_name',
            field=models.BooleanField(default=False, help_text='Should real name be displayed?'),
        ),
        migrations.AlterField(
            model_name='user',
            name='display_name',
            field=models.CharField(default=None, help_text='A unique user name', max_length=200),
        ),
    ]
