# Generated by Django 4.0.2 on 2022-03-14 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0030_user_show_real_name_alter_user_display_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='file_uri',
            field=models.ImageField(null=True, upload_to='posts/attachments/%Y/%m/%d/'),
        ),
    ]
