# Generated by Django 4.0.2 on 2022-03-18 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0031_attachment_file_uri'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='vote_count',
        ),
        migrations.AddField(
            model_name='post',
            name='total_votes_down',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='total_votes_up',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
