# Generated by Django 4.0.2 on 2022-03-22 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0034_smstoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smstoken',
            name='token',
            field=models.CharField(default=None, max_length=256, null=True),
        ),
    ]
