# Generated by Django 4.0.2 on 2022-04-05 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0035_alter_smstoken_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='space',
            name='thumbnail',
            field=models.FilePathField(default=None, path='/static/'),
        ),
    ]
