# Generated by Django 4.0.2 on 2022-04-05 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0036_alter_space_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='space',
            name='thumbnail',
            field=models.FileField(default=None, null=True, upload_to='static/spaces/'),
        ),
    ]
