# Generated by Django 4.0.2 on 2022-07-20 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0039_rename_invitee_id_invitation_invitee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='space',
            name='symbol',
            field=models.TextField(default=None, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='space',
            name='symbol_description',
            field=models.TextField(default=None, max_length=200, null=True),
        ),
    ]
