# Generated by Django 4.0.2 on 2022-07-20 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0040_space_symbol_space_symbol_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='space',
            name='symbol',
            field=models.TextField(default=None, max_length=25, null=True),
        ),
    ]
